// Generated by CoffeeScript 1.6.3
/*
 * Convert swd input text field with sorrounding div into a search form with hidden swd input field
 * @author Robert Kolatzek
 * @copyright Robert Kolatzek
 * @version 1.0
*/


